kind: pipeline
type: docker
name: z2p-axum-ci

# ---------------------------
# Cargo 缓存卷（持久化在 Drone 主机上）
# ---------------------------
volumes:
  - name: cargo-cache
    host:
      # 你可以改为任意 Drone 主机上的可写目录
      path: /var/lib/drone/cargo-cache
  - name: cargo-target
    host:
      path: /var/lib/drone/cargo-target

services:
  - name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newsletter
    command:
      - --default-authentication-plugin=mysql_native_password
      - --port=13306
    ports:
      - 13306

steps:
  # ---------------------------
  # 1️⃣ 等待 MySQL
  # ---------------------------
  - name: wait-for-mysql
    image: mysql:8.0
    commands:
      - |
        echo "Waiting for MySQL service at mysql:13306 ..."
        for i in $(seq 1 60); do
          mysql -h mysql -uroot -p1234 -P 13306 -e "SELECT 1" && exit 0
          sleep 2
        done
        echo "MySQL not reachable on mysql:13306"
        exit 1

  # ---------------------------
  # 2️⃣ cargo test（带缓存）
  # ---------------------------
  - name: test
    image: rust:bookworm
    environment:
      # 覆盖你的配置，连 CI 内的 mysql 服务
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
      # 统一缓存位置（容器内路径）
      CARGO_HOME: /drone/cargo
      CARGO_TARGET_DIR: /drone/target
    volumes:
      - name: cargo-cache
        path: /drone/cargo
      - name: cargo-target
        path: /drone/target
    commands:
      - rustc --version
      - cargo --version
      # 预热依赖缓存（避免 test 步骤第一次编译时拉取索引/依赖）
      - cargo fetch
      # 编译+测试（利用缓存）
      - cargo test --all

  # ---------------------------
  # 3️⃣ tarpaulin 覆盖率（带缓存）
  # ---------------------------
  - name: coverage
    image: ghcr.io/xd009642/tarpaulin:latest
    when:
      branch:
        - main
      event:
        - push
    environment:
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
      # 与 test 步骤一致的缓存路径（非常重要）
      CARGO_HOME: /drone/cargo
      CARGO_TARGET_DIR: /drone/target
    volumes:
      - name: cargo-cache
        path: /drone/cargo
      - name: cargo-target
        path: /drone/target
    commands:
      - mkdir -p /drone/src/coverage
      # 保险起见再 fetch 一次（不同镜像，保证缓存可用）
      - cargo fetch
      - cargo tarpaulin --ignore-tests --out Html --output-dir /drone/src/coverage
      - echo "Coverage generated at /drone/src/coverage"

  # ---------------------------
  # 4️⃣ 打包 coverage.zip（便于下载）
  # ---------------------------
  - name: archive-coverage
    image: alpine:latest
    when:
      branch:
        - main
      event:
        - push
    commands:
      - apk add zip
      - cd /drone/src/coverage
      - zip -r coverage.zip .
      - echo "=========================================="
      - echo "Coverage report ready for download:"
      - echo "➡  Drone UI → Artifacts → coverage/coverage.zip"
      - echo "=========================================="

  # ---------------------------
  # 5️⃣ 构建 Docker 镜像（不 push，无 trusted）
  # ---------------------------
  - name: docker-build
    image: docker:26
    when:
      branch:
        - main
      event:
        - push
    commands:
      - echo "Building Docker image..."
      - docker build -t zero2prod:latest .