kind: pipeline
type: docker
name: z2p-axum-ci-cd

# =====================
# 1️⃣ CI：构建 Rust 二进制 & Docker 镜像
# =====================
steps:
  - name: cargo-build
    image: rust:bookworm
    commands:
      - cargo fmt --all
      - cargo test --all
      - cargo build --release
      - strip target/release/z2p-axum
    cache:
      key: cargo-cache
      paths:
        - /usr/local/cargo/registry
        - /usr/local/cargo/git
        - target

  - name: docker-build
    image: docker:27-cli
    privileged: true
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t zero2prod:latest .
      - docker save zero2prod:latest > zero2prod.tar
      - rm -f zero2prod_old.tar || true
      - mv zero2prod.tar zero2prod_old.tar

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

# =====================
# 2️⃣ CD：部署到生产服务器
# =====================
---

kind: pipeline
type: docker
name: z2p-axum-cd

steps:
  - name: deploy
    image: appleboy/drone-ssh
    privileged: true
    environment:
      PROD_DB_HOST:
        from_secret: PROD_DB_HOST
      PROD_DB_PORT:
        from_secret: PROD_DB_PORT
      PROD_DB_USER:
        from_secret: PROD_DB_USER
      PROD_DB_PASSWORD:
        from_secret: PROD_DB_PASSWORD
      PROD_DB_NAME:
        from_secret: PROD_DB_NAME
    settings:
      host:
        from_secret: SSH_HOST
      port:
        from_secret: SSH_PORT
      username:
        from_secret: SSH_USER
      password:
        from_secret: SSH_PASSWORD
      script:
        - set -euo pipefail
        - APP_DIR="$HOME/zero2prod"
        - mkdir -p "$APP_DIR"
        - cd "$APP_DIR"

        # 上传最新镜像
        - scp /drone/src/zero2prod_old.tar $SSH_USER@$SSH_HOST:$APP_DIR/zero2prod.tar

        # 服务器上加载并运行 Docker
        - ssh $SSH_USER@$SSH_HOST " \
            docker load < $APP_DIR/zero2prod.tar && \
            docker stop zero2prod || true && \
            docker rm zero2prod || true && \
            docker run -d \
              --name zero2prod \
              -p 18000:8000 \
              -e APP_ENVIRONMENT=production \
              -e APP_DATABASE__HOST=$PROD_DB_HOST \
              -e APP_DATABASE__PORT=$PROD_DB_PORT \
              -e APP_DATABASE__USERNAME=$PROD_DB_USER \
              -e APP_DATABASE__PASSWORD=$PROD_DB_PASSWORD \
              -e APP_DATABASE__DATABASE_NAME=$PROD_DB_NAME \
              -e APP_DATABASE__REQUIRE_SSL=false \
              zero2prod:latest \
              && docker image prune -f \
          "
