kind: pipeline
type: docker
name: z2p-axum-ci

platform:
  os: linux
  arch: amd64

# ======== 服务容器：MySQL（测试用） ========
services:
  - name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newsletter
    command:
      - --default-authentication-plugin=mysql_native_password
      - --port=13306
    ports:
      - 13306

# ======== Cargo 缓存（需要仓库 Trusted） ========
volumes:
  - name: cargo-registry
    host:
      path: /var/lib/drone/cargo/registry
  - name: cargo-git
    host:
      path: /var/lib/drone/cargo/git
  - name: cargo-target
    host:
      path: /var/lib/drone/cargo/target

# ======== CI 步骤 ========
steps:
  - name: wait-for-mysql
    image: mysql:8.0
    commands:
      - |
        echo "Waiting for MySQL at mysql:13306 ..."
        for i in $(seq 1 120); do
          mysql -h mysql -uroot -p1234 -P 13306 -e "SELECT 1" && exit 0
          sleep 2
        done
        echo "MySQL not reachable on mysql:13306"
        exit 1


  - name: test
    image: rust:bookworm
    environment:
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
    volumes:
      - name: cargo-registry
        path: /usr/local/cargo/registry
      - name: cargo-git
        path: /usr/local/cargo/git
      - name: cargo-target
        path: /drone/src/target
    commands:
      - cargo test --all --locked --workspace

  - name: coverage
    image: xd009642/tarpaulin:latest
    pull: if-not-exists
    privileged: true
    environment:
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
    volumes:
      - name: cargo-registry
        path: /usr/local/cargo/registry
      - name: cargo-git
        path: /usr/local/cargo/git
      - name: cargo-target
        path: /drone/src/target
    commands:
      - |
        cargo tarpaulin --out Html --out Lcov || {
          echo "tarpaulin failed"; exit 1;
        }
        test -f tarpaulin-report.html || { echo "report missing"; exit 1; }
        echo "Coverage HTML: ./tarpaulin-report.html"


  # ======== 把覆盖率报告同步到目标机用户家目录（~） ========
  - name: scp-coverage-to-user-home
    image: appleboy/drone-scp
    when:
      branch:
        - main
      event:
        - push
        - tag
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      password:
        from_secret: SSH_PASSWORD
      port:
        from_secret: SSH_PORT
      target: "~"
      source:
        - tarpaulin-report.html
        - lcov.info
      overwrite: true
      command_timeout: 2m


