kind: pipeline
type: docker
name: z2p-axum-ci

services:
  - name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newsletter
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306  # 使用默认端口

steps:
  - name: wait-for-mysql
    image: mysql:8.0
    commands:
      - |
        for i in $(seq 1 30); do
          mysql -h mysql -uroot -p1234 -P 3306 -e "SELECT 1" && exit 0
          sleep 2
        done
        exit 1

  - name: test
    image: rust:bookworm
    environment:
      APP_ENVIRONMENT: local
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASS: 1234
      DATABASE_NAME: newsletter
    commands:
      - cargo test

  - name: coverage
    image: ghcr.io/xd009642/tarpaulin:latest
    when:
      branch:
        - main
      event:
        - push
    environment:
      APP_ENVIRONMENT: local
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASS: 1234
      DATABASE_NAME: newsletter
    commands:
      - mkdir -p /drone/src/coverage
      - cargo tarpaulin --out Html --output-dir /drone/src/coverage --engine llvm --timeout 120 --exclude-files "target/*"

  - name: docker-build
    image: docker:26
    when:
      branch:
        - main
      event:
        - push
    commands:
      - echo "Building Docker image..."
      - if [ "$DRONE_REPO_TRUSTED" = "true" ]; then docker build -t z2p-axum:latest .; else echo "Skipping docker build for untrusted repo"; fi

trigger:
  branch:
    - main