kind: pipeline
type: docker
name: z2p-axum-ci-check

steps:
  - name: check-secrets-and-docker
    image: docker:24-dind
    privileged: true
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - set -e
      - echo "🔹 Checking Drone Secrets..."
      - echo "DOCKER_REGISTRY=${DOCKER_REGISTRY}"
      - echo "DOCKER_USERNAME=${DOCKER_USERNAME}"
      - if [ -n "${DOCKER_PASSWORD}" ]; then echo "DOCKER_PASSWORD is set"; else echo "DOCKER_PASSWORD missing"; fi

      - echo "🔹 Testing Docker login..."
      - |
        echo "${DOCKER_PASSWORD}" | docker login "${DOCKER_REGISTRY}" -u "${DOCKER_USERNAME}" --password-stdin

      - echo "🔹 Docker login successful, checking info..."
      - docker --config /root/.docker info

      - echo "✅ Secrets and Docker login test passed"
