kind: pipeline
type: docker
name: z2p-axum-ci-cd

services:
  - name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newsletter
    command:
      - --default-authentication-plugin=mysql_native_password
      - --port=13306
    ports:
      - 13306

steps:
  # =====================
  # 1️⃣ 等 MySQL 就绪（CI 用）
  # =====================
  - name: wait-for-mysql
    image: mysql:8.0
    commands:
      - |
        echo "Waiting for MySQL service at mysql:13306 ..."
        for i in $(seq 1 60); do
          mysql -h mysql -uroot -p1234 -P 13306 -e "SELECT 1" && exit 0
          sleep 2
        done
        echo "MySQL not reachable on mysql:13306"
        exit 1

  # =====================
  # 2️⃣ 测试（可暂时关闭）
  # =====================
  # - name: test
  #   image: rust:bookworm
  #   environment:
  #     APP_DATABASE__HOST: mysql
  #     APP_DATABASE__PORT: "13306"
  #     APP_DATABASE__USERNAME: root
  #     APP_DATABASE__PASSWORD: 1234
  #     APP_DATABASE__DATABASE_NAME: newsletter
  #     APP_DATABASE__REQUIRE_SSL: "false"
  #   commands:
  #     - cargo test

  # =====================
  # 3️⃣ 部署（服务器 build & run）
  # =====================
  - name: deploy
    image: appleboy/drone-ssh
    environment:
      PROD_DB_HOST:
        from_secret: PROD_DB_HOST
      PROD_DB_PORT:
        from_secret: PROD_DB_PORT
      PROD_DB_USER:
        from_secret: PROD_DB_USER
      PROD_DB_PASSWORD:
        from_secret: PROD_DB_PASSWORD
      PROD_DB_NAME:
        from_secret: PROD_DB_NAME
    settings:
      host:
        from_secret: SSH_HOST
      port:
        from_secret: SSH_PORT
      username:
        from_secret: SSH_USER
      password:
        from_secret: SSH_PASSWORD
      script:
        - |
          set -e

          APP_DIR="$HOME/zero2prod"
          REPO_URL="https://github.com/你的github用户名/你的仓库.git"

          echo "==> Prepare app directory"
          if [ ! -d "$APP_DIR" ]; then
            echo "Directory not found, cloning repository..."
            git clone "$REPO_URL" "$APP_DIR"
          elif [ ! -d "$APP_DIR/.git" ]; then
            echo "Directory exists but is not a git repo, removing and cloning..."
            rm -rf "$APP_DIR"
            git clone "$REPO_URL" "$APP_DIR"
          else
            echo "Directory exists and is a git repo, pulling latest code..."
            cd "$APP_DIR"
            git reset --hard
            git clean -fd
            git pull
          fi

          cd "$APP_DIR"

          echo "==> Build docker image on server"
          docker build -t zero2prod:latest .

          echo "==> Restart container"
          docker stop zero2prod || true
          docker rm zero2prod || true

          docker run -d \
            --name zero2prod \
            -p 18000:8000 \
            -e APP_ENVIRONMENT=production \
            -e APP_DATABASE__HOST=$PROD_DB_HOST \
            -e APP_DATABASE__PORT=$PROD_DB_PORT \
            -e APP_DATABASE__USERNAME=$PROD_DB_USER \
            -e APP_DATABASE__PASSWORD=$PROD_DB_PASSWORD \
            -e APP_DATABASE__DATABASE_NAME=$PROD_DB_NAME \
            -e APP_DATABASE__REQUIRE_SSL=false \
            zero2prod:latest
