- name: deploy
    image: appleboy/drone-ssh
    when:
      branch:
        - main
      event:
        - push
        - tag
    environment:
      PROD_DB_HOST:
        from_secret: PROD_DB_HOST
      PROD_DB_PORT:
        from_secret: PROD_DB_PORT
      PROD_DB_USER:
        from_secret: PROD_DB_USER
      PROD_DB_PASSWORD:
        from_secret: PROD_DB_PASSWORD
      PROD_DB_NAME:
        from_secret: PROD_DB_NAME
      # 生产未开 TLS，默认 false；未来启用 TLS 时把这个变量改为 "true" 即可
      PROD_DB_REQUIRE_SSL: "false"
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      password:
        from_secret: SSH_PASSWORD
      port:
        from_secret: SSH_PORT
      command_timeout: 12m
      script:
        - |
          set -euo pipefail

          TAR_TMP=/tmp/zero2prod-${DRONE_COMMIT_SHA}.tar
          COV_HTML_TMP=/tmp/tarpaulin-report.html
          COV_LCOV_TMP=/tmp/lcov.info

          # 0) 把 /tmp 的工件移动到用户家目录（~）
          [ -f "$COV_HTML_TMP" ] && mv -f "$COV_HTML_TMP" ~/
          [ -f "$COV_LCOV_TMP" ] && mv -f "$COV_LCOV_TMP"  ~/
          [ -f "$TAR_TMP" ]      && mv -f "$TAR_TMP"       ~/

          # 1) 停/删旧容器
          if docker ps -a --format '{{.Names}}' | grep -q '^zero2prod$'; then
            docker stop zero2prod || true
            docker rm   zero2prod || true
          fi

          # 2) 本地加载镜像 tar，并打上易用标签
          TAR=~/zero2prod-${DRONE_COMMIT_SHA}.tar
          if [ ! -f "${TAR}" ]; then
            echo "image tar not found: ${TAR}"
            exit 1
          fi

          docker load -i "${TAR}"

          # 取出刚加载的 ci-tag 对应的镜像 ID，并打 tag: latest / ${DRONE_COMMIT_SHA}
          IMAGE_ID=$(docker images --format '{{.Repository}}:{{.Tag}} {{.ID}}' \
            | awk "/zero2prod:ci-${DRONE_COMMIT_SHA}/{print \$2}" | head -n1)

          if [ -z "${IMAGE_ID:-}" ]; then
            echo "loaded image not found for ci-${DRONE_COMMIT_SHA}"
            exit 1
          fi

          docker tag "${IMAGE_ID}" zero2prod:latest
          docker tag "${IMAGE_ID}" zero2prod:${DRONE_COMMIT_SHA}

          # 3) 运行新容器（默认不强制 SSL；如启用 TLS，把 PROD_DB_REQUIRE_SSL 改为 true 即可）
          docker run -d --name zero2prod \
            --restart=always \
            -p 8000:8000 \
            -e APP_ENVIRONMENT=production \
            -e APP_DATABASE__HOST=${PROD_DB_HOST} \
            -e APP_DATABASE__PORT=${PROD_DB_PORT} \
            -e APP_DATABASE__USERNAME=${PROD_DB_USER} \
            -e APP_DATABASE__PASSWORD=${PROD_DB_PASSWORD} \
            -e APP_DATABASE__DATABASE_NAME=${PROD_DB_NAME} \
            -e APP_DATABASE__REQUIRE_SSL=${PROD_DB_REQUIRE_SSL} \
            zero2prod:latest

          # 4) 健康检查
          echo "Probing /health_check ..."
          ok=0
          for i in $(seq 1 60); do
            if curl -fsS http://127.0.0.1:8000/health_check >/dev/null; then
              echo "✅ health OK"
              ok=1
              break
            fi
            sleep 2
          done
          if [ "${ok}" != "1" ]; then
            echo "❌ health check failed"
            docker logs zero2prod
            exit 1
          fi

          # 5) 清理非必要数据：镜像/容器垃圾 + 临时 tar
          docker image prune -f || true
          docker container prune -f || true
          rm -f "${TAR}" || true