kind: pipeline
type: docker
name: z2p-axum-ci

platform:
  os: linux
  arch: amd64

# =============================
# MySQL 服务容器（测试用）
# =============================
services:
  - name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newsletter
    command:
      - --default-authentication-plugin=mysql_native_password
      - --port=13306
    ports:
      - 13306

# =============================
# Host Volumes（需要 Trusted）
# =============================
volumes:
  - name: cargo-registry
    host:
      path: /var/lib/drone/cargo/registry

  - name: cargo-git
    host:
      path: /var/lib/drone/cargo/git

  - name: cargo-target
    host:
      path: /var/lib/drone/cargo/target

  - name: coverage-output
    host:
      path: /var/lib/drone/artifacts/coverage

# =============================
# CI Steps
# =============================
steps:

  # 等待 MySQL 启动
  - name: wait-for-mysql
    image: mysql:8.0
    commands:
      - |
        echo "Waiting for MySQL at mysql:13306 ..."
        for i in $(seq 1 120); do
          mysql -h mysql -uroot -p1234 -P 13306 -e "SELECT 1" && exit 0
          sleep 2
        done
        echo "MySQL not reachable"
        exit 1

  # 运行测试
  - name: test
    image: rust:bookworm
    environment:
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
    volumes:
      - name: cargo-registry
        path: /usr/local/cargo/registry
      - name: cargo-git
        path: /usr/local/cargo/git
      - name: cargo-target
        path: /drone/src/target
    commands:
      - cargo test --all --locked --workspace

  # 生成覆盖率并保存到服务器
  - name: coverage
    image: xd009642/tarpaulin:latest
    privileged: true
    environment:
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
    volumes:
      - name: cargo-registry
        path: /usr/local/cargo/registry
      - name: cargo-git
        path: /usr/local/cargo/git
      - name: cargo-target
        path: /drone/src/target
      - name: coverage-output
        path: /coverage
    commands:
      - echo "Running tarpaulin..."
      - cargo tarpaulin --out Html --out Lcov

      - echo "Saving coverage to host..."

      # 每个构建独立目录
      - mkdir -p /coverage/${DRONE_BUILD_NUMBER}

      - cp tarpaulin-report.html /coverage/${DRONE_BUILD_NUMBER}/
      - cp lcov.info /coverage/${DRONE_BUILD_NUMBER}/

      # 更新 latest
      - rm -rf /coverage/latest
      - cp -r /coverage/${DRONE_BUILD_NUMBER} /coverage/latest

      - echo "Coverage saved:"
      - echo "/var/lib/drone/artifacts/coverage/${DRONE_BUILD_NUMBER}"
