kind: pipeline
type: docker
name: z2p-axum-ci

platform:
  os: linux
  arch: amd64

############################################
# MySQL 服务容器（测试用）
############################################
services:
  - name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newsletter
    command:
      - --default-authentication-plugin=caching_sha2_password
      - --port=13306
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306

############################################
# Host Volumes（需要 Trusted 仓库）
############################################
volumes:
  - name: cargo-registry
    host:
      path: /var/lib/drone/cargo/registry

  - name: cargo-git
    host:
      path: /var/lib/drone/cargo/git

  - name: cargo-target
    host:
      path: /var/lib/drone/cargo/target

  - name: coverage-output
    host:
      path: /var/lib/drone/artifacts/coverage

############################################
# CI Steps
############################################
steps:

  ##########################################
  # 等待 MySQL 启动
  ##########################################
  - name: wait-for-mysql
    image: mysql:8.0
    commands:
      - |
        echo "Waiting for MySQL..."
        for i in $(seq 1 120); do
          mysql -h mysql -uroot -p1234 -P 13306 --protocol=TCP -e "SELECT 1" >/dev/null 2>&1 && {
            echo "MySQL is ready!"
            exit 0
          }
          sleep 2
        done
        echo "MySQL failed to start"
        exit 1

  ##########################################
  # 生成覆盖率（依赖 test 成功）
  ##########################################
  - name: coverage
    image: xd009642/tarpaulin:latest
    privileged: true
    depends_on:
      - wait-for-mysql
    environment:
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
    volumes:
      - name: cargo-registry
        path: /usr/local/cargo/registry
      - name: cargo-git
        path: /usr/local/cargo/git
      - name: cargo-target
        path: /drone/src/target
      - name: coverage-output
        path: /coverage
    commands:
      - echo "Running tarpaulin..."
      - cargo fetch
      - cargo tarpaulin --out Html --out Lcov --all --workspace

      - echo "Saving coverage..."

      - mkdir -p /coverage/${DRONE_BUILD_NUMBER}
      - cp tarpaulin-report.html /coverage/${DRONE_BUILD_NUMBER}/
      - cp lcov.info /coverage/${DRONE_BUILD_NUMBER}/

      - rm -rf /coverage/latest
      - cp -r /coverage/${DRONE_BUILD_NUMBER} /coverage/latest

      - echo "Cleaning old coverage builds (keep latest 2)..."

      - |
        cd /coverage
        ls -1d [0-9]* 2>/dev/null | sort -nr | tail -n +3 | while read dir; do
          echo "Removing old build: $dir"
          rm -rf "$dir"
        done

      - echo "Coverage saved to:"
      - echo "/var/lib/drone/artifacts/coverage/${DRONE_BUILD_NUMBER}"
