kind: pipeline
type: docker
name: z2p-axum-ci

# 用一个共享的缓存卷
volumes:
  - name: cargo-cache
    host:
      path: /var/lib/drone/cargo-cache

steps:
  # Restore cache
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cargo-cache
        path: /cache
    settings:
      restore: true
      mount:
        - /root/.cargo/registry
        - /root/.cargo/git
        - /drone/src/target
      cache_key: cargo-{{ checksum "Cargo.lock" }}

  # MySQL service
services:
  - name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newsletter
    command:
      - --default-authentication-plugin=mysql_native_password
      - --port=13306
    ports:
      - 13306

steps:
  # Wait for MySQL
  - name: wait-for-mysql
    image: mysql:8.0
    commands:
      - |
        echo "Waiting for MySQL service at mysql:13306 ..."
        for i in $(seq 1 60); do
          mysql -h mysql -uroot -p1234 -P 13306 -e "SELECT 1" && exit 0
          sleep 2
        done
        exit 1

  # Run tests (benefits from cache!)
  - name: test
    image: rust:bookworm
    environment:
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
    volumes:
      - name: cargo-cache
        path: /cache
    commands:
      # map cache paths
      - ln -s /cache/registry /root/.cargo/registry || true
      - ln -s /cache/git /root/.cargo/git || true
      - ln -s /cache/target /drone/src/target || true

      # now build with cache
      - cargo test --all

  # Coverage (no privileged, use LLVM)
  - name: coverage
    image: rust:bookworm
    when:
      branch:
        - main
      event:
        - push
    volumes:
      - name: cargo-cache
        path: /cache
    environment:
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
    commands:
      # map cache
      - ln -s /cache/registry /root/.cargo/registry || true
      - ln -s /cache/git /root/.cargo/git || true
      - ln -s /cache/target /drone/src/target || true

      # llvm-coverage
      - rustup component add llvm-tools-preview
      - export RUSTFLAGS="-Cinstrument-coverage"
      - export LLVM_PROFILE_FILE="prof-%p-%m.profraw"
      - cargo test --all

      # generate report
      - mkdir -p /drone/src/coverage
      - llvm-profdata merge -sparse prof-*.profraw -o /drone/src/coverage/coverage.profdata
      - llvm-cov show \
          target/debug/your_binary \
          -instr-profile=/drone/src/coverage/coverage.profdata \
          -output-dir=/drone/src/coverage \
          -format=html

  # Archive coverage report
  - name: archive-coverage
    image: alpine:latest
    when:
      branch:
        - main
      event:
        - push
    commands:
      - apk add zip
      - cd /drone/src/coverage
      - zip -r coverage.zip .

  # Rebuild cache
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cargo-cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - /root/.cargo/registry
        - /root/.cargo/git
        - /drone/src/target
      cache_key: cargo-{{ checksum "Cargo.lock" }}

  # Build Docker image
  - name: docker-build
    image: docker:26
    when:
      branch:
        - main
      event:
        - push
    commands:
      - docker build -t zero2prod:latest .