kind: pipeline
type: docker
name: z2p-axum-ci

services:
  - name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newsletter
    command:
      - --default-authentication-plugin=mysql_native_password
      - --port=13306
    ports:
      - 13306

steps:
  # 1) 等待 MySQL
  - name: wait-for-mysql
    image: mysql:8.0
    commands:
      - |
        echo "Waiting for MySQL service at mysql:13306 ..."
        for i in $(seq 1 60); do
          mysql -h mysql -uroot -p1234 -P 13306 -e "SELECT 1" && exit 0
          sleep 2
        done
        echo "MySQL not reachable on mysql:13306"
        exit 1

  # 2) cargo test
  - name: test
    image: rust:bookworm
    environment:
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
    commands:
      - cargo test --all

  # 3) 覆盖率（用 rust:bookworm 安装 tarpaulin）
  - name: coverage
    image: rust:bookworm
    # tarpaulin 需要 ptrace；首选 privileged。如果 Runner 禁止，请看下方“若无法使用 privileged”
    privileged: true
    when:
      branch:
        - main
      event:
        - push
    environment:
      APP_DATABASE__HOST: mysql
      APP_DATABASE__PORT: "13306"
      APP_DATABASE__USERNAME: root
      APP_DATABASE__PASSWORD: 1234
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__REQUIRE_SSL: "false"
    commands:
      # 安装 tarpaulin（--locked 更稳定；首次会稍慢，后续可配缓存加速）
      - cargo install cargo-tarpaulin --locked
      # 生成 HTML 报告到 /drone/src/coverage（Drone 的工作区）
      - mkdir -p /drone/src/coverage
      - cargo tarpaulin --ignore-tests --out Html --output-dir /drone/src/coverage
      - echo "Coverage generated at /drone/src/coverage"

  # 4) 打包 coverage.zip，便于在 Drone Web UI → Artifacts 下载
  - name: archive-coverage
    image: alpine:latest
    when:
      branch:
        - main
      event:
        - push
    commands:
      - apk add --no-cache zip
      - cd /drone/src/coverage
      - zip -r coverage.zip .
      - echo "=========================================="
      - echo "Coverage report ready for download:"
      - echo "➡  Drone UI → Artifacts → coverage/coverage.zip"
      - echo "=========================================="

  # 5) 构建 Docker 镜像（不 push；与 trusted 无关）
  - name: docker-build
    image: docker:26
    when:
      branch:
        - main
      event:
        - push
    commands:
      - echo "Building Docker image..."
      - docker build -t zero2prod:latest .