//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
pub use crate::entity::subscription::ActiveModel as SubscriptionsActiveModel;
pub use crate::entity::subscription::Entity as SubscriptionsEntity;
pub use crate::entity::subscription::Model as SubscriptionsModel;
