//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
pub use crate::entity::subscriptions::Entity as SubscriptionsEntity;
pub use crate::entity::subscriptions::Model as SubscriptionsModel;
pub use crate::entity::subscriptions::ActiveModel as SubscriptionsActiveModel;
