//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "subscriptions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub email: String,
    pub name: String,
    pub subscribed_at: DateTimeUtc,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::subscription_tokens::Entity")]
    SubscriptionTokens,
}

impl Related<super::subscription_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
